# general
data_dir: vbts_video
gpu_config: configs/gpu_config_7b.json
cuda: 0
seed: 0
exps_path: exps_7b
train: True
val: False
test: True



# encoder
videomae_model_name: MCG-NJU/videomae-base 
freeze_encoder: True
encoder_path: vtvllm/ckpt/vbts_encoder.pt
encoder_output_size: 768 

# projection
freeze_projection: False
projection_lr: 0.0002
projection_path: null # stage2
# projection_path: xxx/project.pt # stage3

# LLM
train_files: [vtvllm/vbts_video/train_qa.json]
val_files: [vtvllm/vbts_video/val_tfa_qa.json]
test_files: [vtvllm/vbts_video/test_qa.json]
model_type: qwen2.5-7b  
cutoff_len: 512
offload_dir: ./
llm_lr: 0.0002
quantized: False
tokenizer_path: null # stage2
llm_path: null # stage2
# tokenizer_path: xxx/tokenizer # stage3
# llm_path: xxx/llm_weights # stage3

## LoRA
lora_trained: False
use_lora: False # stage2
# use_lora: True # stage3
lora_alpha: 256
r: 128
lora_dropout: 0.05
target_modules:
  - q_proj
  - k_proj
modules_to_save:
  - embed_tokens
bias: none
## train
max_train_steps: 10000
save_freq: null
per_device_train_batch_size: 1
llm_gradient_accumulation_steps: 16
warmup_steps: 0.03
## val
per_device_val_batch_size: 1
## generation
max_new_tokens:
  default: 200
  train_tactile_feature_assessment: 120
  train_surface_feature_distinction: 200
  train_surface_optimality_identification: 220
  train_object_sensation_correlation: 220
  test_tactile_feature_assessment: 120
  test_surface_feature_distinction: 200
  test_surface_optimality_identification: 220
  test_object_sensation_correlation: 220
  eval_tactile_feature_assessment: 120
  eval_surface_feature_distinction: 200
  eval_surface_optimality_identification: 220
  eval_object_sensation_correlation: 220
  eval_tactile_scenario_analysis: 220
